name = "whatnext-frontend"
pages_build_output_dir = "out"
compatibility_date = "2024-08-12"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "movie-recommendations-db"
database_id = "a456b5dc-1c83-4373-b611-da83830fef68"

# KV Namespaces
[[kv_namespaces]]
binding = "MOVIE_QUESTIONS"
id = "6089d3c9342d4a15830dc5cd4dd73323"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "c7e6e8fd74b740d3969f5c8584c47482"

[[kv_namespaces]]
binding = "MOVIE_CACHE"
id = "4a7d878803284d71901923a4194412f1"

[[kv_namespaces]]
binding = "VECTOR_CACHE"
id = "da01e2fdc26a40e480160bf1ac6bfac6"

[[kv_namespaces]]
binding = "PREFERENCE_VECTORS"
id = "53a93865233e44a1ad1b5983a5de3e28"

# Vectorize Binding
[[vectorize]]
binding = "MOVIE_VECTORS"
index_name = "whatnext-movies"

# Environment Variables
[vars]
VECTORIZE_WORKER_URL = "https://whatnext-vectorize.jhaladik.workers.dev"
CLAUDE_API_ENDPOINT = "https://api.anthropic.com/v1/messages"
CLAUDE_MODEL = "claude-3-5-sonnet-20241022"
MAX_QUESTIONS_PER_SESSION = 5
SESSION_TIMEOUT_SECONDS = 3600
LOG_LEVEL = "debug"
ENABLE_CLAUDE_FALLBACK = false
ENABLE_ANALYTICS = true
DEFAULT_DOMAIN = "movies"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"